sudo: required
services:
  - docker
before_install:
  # copy and decrypt secure file that I updated using travisci-cli into this travis container
  - openssl aes-256-cbc -K $encrypted_3db9a6afcade_key -iv $encrypted_3db9a6afcade_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | base > /dev/null;
  # look at default install dir and apply this default config
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # auth to gcloud
  - gcloud auth activate-service-account --key-file service-account.json
  # select project and zone
  - gcloud config set project multi-k8s-270020
  - gcloud config set compute/zone us-central1-c
  # work with this cluster
  - gcloud container clusters get-credentials multi-cluster
